// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSIMRS.Data;

#nullable disable

namespace MiniSIMRS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MiniSIMRS.Models.Dokter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaDokter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoSIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spesialisasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dokters");
                });

            modelBuilder.Entity("MiniSIMRS.Models.Pasien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoRekamMedis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pasiens");
                });

            modelBuilder.Entity("MiniSIMRS.Models.RekamMedis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DokterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeluhanUtama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PasienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResepObat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalPeriksa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tindakan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DokterId");

                    b.HasIndex("PasienId");

                    b.ToTable("RekamMediss");
                });

            modelBuilder.Entity("MiniSIMRS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PashwordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiniSIMRS.Models.RekamMedis", b =>
                {
                    b.HasOne("MiniSIMRS.Models.Dokter", "Dokter")
                        .WithMany("RekamMediss")
                        .HasForeignKey("DokterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSIMRS.Models.Pasien", "Pasien")
                        .WithMany("RekamMediss")
                        .HasForeignKey("PasienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dokter");

                    b.Navigation("Pasien");
                });

            modelBuilder.Entity("MiniSIMRS.Models.Dokter", b =>
                {
                    b.Navigation("RekamMediss");
                });

            modelBuilder.Entity("MiniSIMRS.Models.Pasien", b =>
                {
                    b.Navigation("RekamMediss");
                });
#pragma warning restore 612, 618
        }
    }
}
